### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by Its-Vichy** [Snowwy1337/Vichy-DiscordTokenGen-Leak-Full-Source#1]
Thanks for full credit but, if i took the the repo is not to see other people repost it..
Many skid are selling it and it will be patched if people are posting the SRC.

The project is free to use but the src will still get closed

**Comment by Snowwy1337** [comment]
Alrighty, but you posted it yourself? no?

**Comment by Its-Vichy** [comment]
reposted cuz everybody think they have leak LMFAO

**Comment by Snowwy1337** [comment]
do you want me to take this down or not

**Comment by Snowwy1337** [comment]
it doesnt have the new image serer linked, and I don't think I'll ever be linking it, I doubt retarded skins would be able to fix it :P

**Comment by Its-Vichy** [comment]
you can keep it

**Comment by Snowwy1337** [comment]
alrighty
