### ISSUE TITLE
bro can u help??

### ISSUE THREAD

**Issue by beaste69** [Snowwy1337/Vichy-DiscordTokenGen-Leak-Full-Source#2]
![image](https://user-images.githubusercontent.com/98755775/184575047-e419a478-c859-4821-acd8-811342f57793.png)

**Comment by Snowwy1337** [comment]
install the module you retard, if you cannot read, you shouldnt be using it.

**Comment by Snowwy1337** [comment]
install the module you retard, if you cannot read, you shouldnt be using it.
